trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']
pool:
  vmImage: 'vs2017-win2016'
steps:
- task: Rust@1
  inputs:
    installNightly: false
- task: Cargo@1
  inputs:
    cargoCommand: 'test --release'
    verbose: false
  displayName: Cargo
  env:
    LZZZZ_FUZZER_ITERATION: 100000
