trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']
pool:
  vmImage: 'vs2017-win2016'
variables:
  CARGO_CACHE_FOLDER: $(Pipeline.Workspace)/target
steps:
- task: Cache@2
  inputs:
    key: 'cargo | "$(Agent.OS)" | Cargo.toml'
    restoreKeys: |
       cargo | "$(Agent.OS)"
       cargo
    path: $(CARGO_CACHE_FOLDER)
  displayName: Cache Cargo packages
- task: Rust@1
  inputs:
    installNightly: false
- task: Cargo@1
  inputs:
    cargoCommand: 'test --release --all-features'
    verbose: true
  displayName: Cargo
  env:
    LZZZZ_FUZZER_ITERATION: 100000
