trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']
pool:
  name: Azure Pipelines
steps:
- task: Rust@1
  inputs:
    installNightly: false
- task: Cargo@1
  inputs:
    cargoCommand: 'test --all-features --release'
    verbose: false
  displayName: Cargo
  env:
    LZZZZ_FUZZER_ITERATION: 1000000
