[package]
name = "lzzzz"
version = "0.1.0"
authors = ["picoHz <picoHz@outlook.com>"]
edition = "2018"
description = "Yet another liblz4 binding."
keywords = ["lz4", "lz4f", "lz4-hc", "compression", "decompression", "async"]
categories = ["compression", "api-bindings"]
repository = "https://github.com/picoHz/lzzzz"
homepage = "https://github.com/picoHz/lzzzz"
documentation = "https://docs.rs/lzzzz"
include = ["src/**/*", "build.rs", "vendor/liblz4/*", "Cargo.toml"]

[dependencies]
tokio = { version = "0.2.21", optional = true }
pin-project = { version = "0.4.22", optional = true }

[dev-dependencies]
rand = { version = "0.7.3", features = ["small_rng"] }
tokio = { version = "0.2.21", features = ["fs", "rt-core", "rt-threaded", "macros"] }
lazy_static = "1.4.0"
bytes = "0.5.5"
assert_fs = "1.0.0"
futures = "0.3.5"
rayon = "1.3.1"

[build-dependencies]
cc = { version = "1.0.57", features = ["parallel"] }

[features]
tokio-io = ["tokio/io-util", "pin-project"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
