[package]
name = "lzzzz"
version = "0.1.0"
authors = ["picoHz <picoHz@outlook.com>"]
edition = "2018"
keywords = ["lz4", "lz4f", "lz4-hc", "compression", "decompression"]
categories = ["compression", "api-bindings"]
repository = "https://github.com/picoHz/lzzzz"
homepage = "https://github.com/picoHz/lzzzz"
documentation = "https://docs.rs/lzzzz"
include = ["src/**/*", "build.rs", "vendor/liblz4/lib/*", "Cargo.toml"]

[dependencies]
libc = "0.2.71"
tokio = { version = "0.2.21", optional = true }

[dev-dependencies]
rayon = "1.3.0"
rand = { version = "0.7.3", features = ["small_rng"] }
pbr = "1.0.3"

[build-dependencies]
cc = "1.0.54"

[features]
default = ["lz4-use-stack", "use-tls"]

tokio-io = ["tokio"]
use-tls = []
lz4-use-stack = []
lz4hc-use-stack = []
liblz4-experimental = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
